export const SET_FFMPEG_STATE = "SET_FFMPEG_STATE"
export const SET_MEDIA_SRC_STATE = "SET_MEDIA_SRC_STATE"
export const SET_OUTPUT_TYPE = "SET_OUTPUT_TYPE"
export const SET_PROGRESS_PERCENTAGE =
  "SET_PROGRESS_PERCENTAGE"
export const SET_MEDIA_OUTPUT = "SET_MEDIA_OUTPUT"
export const START_CONVERT_PROGRESS =
  "START_CONVERT_PROGRESS"
export const STOP_CONVERT_PROGRESS = "STOP_CONVERT_PROGRESS"
